[package]
name = "ncspot"
version = "0.1.0"
authors = ["Henrik Friedrichsen <henrik@affekt.org>"]
edition = "2018"

[dependencies]
cursive = "0.10"
crossbeam-channel = "0.3.8"
env_logger = "0.5.13"
failure = "0.1.3"
futures = "0.1"
log = "0.4.6"
rspotify = "0.2.5"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
tokio-core = "0.1"
unicode-width = "0.1.5"
# cursive_tree_view = "0.3.0"
cursive_tree_view = { path = "../cursive_tree_view" }
derive_more = "0.14.0"

[dependencies.librespot]
git = "https://github.com/librespot-org/librespot.git"
default-features = false

[features]
pulseaudio_backend = ["librespot/pulseaudio-backend"]
portaudio_backend = ["librespot/portaudio-backend"]
default = ["pulseaudio_backend"]
